# Generated by Django 4.2.1 on 2024-09-10 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_question_is_answered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_value',
            field=models.IntegerField(default=0),
        ),
    ]
