# Generated by Django 4.2.1 on 2024-09-24 04:34

import django.contrib.postgres.fields
from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_lobby_remove_question_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='is_ended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lobby',
            name='player_id',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lobby',
            name='pos',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=games.models.default_settings, size=None),
        ),
        migrations.AddField(
            model_name='lobby',
            name='rand_value',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=games.models.default_settings, size=None),
        ),
    ]
