# Generated by Django 4.2.1 on 2024-11-03 03:19

import django.contrib.postgres.fields
from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_gamesizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_answered',
        ),
        migrations.AddField(
            model_name='lobby',
            name='map',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=games.models.default_settings, size=None),
        ),
    ]
