# Generated by Django 4.2.1 on 2024-11-03 03:44

import django.contrib.postgres.fields
from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_alter_lobby_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='map',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=games.models.empty_list, size=None),
        ),
    ]
